[settings]
experimental = true # Required to use lockfile.
lockfile = true     # DO NOT FORGET TO `touch mise.lock` if mise.lock does not exist!


[tools]
neovim = 'latest'

#--- Test & Lint
# Static checker for GitHub Actions workflow files.
actionlint = 'latest'
# An opinionated Lua code formatter
stylua = 'latest'
# A CLI tool for code structural search, lint and rewriting.
ast-grep = 'latest'


[tasks.test]
alias = 'default'
description = 'Run all linters and tests'
depends = ['lint:*', 'test:*']

[tasks.lint]
description = 'Run all linters'
depends = ['lint:*']

[tasks.'lint:workflows']
description = 'Lint GitHub Action workflows'
run = 'actionlint'

[tasks.'lint:stylua']
description = 'Lint Lua code'
run = 'stylua --check .'

[tasks.'lint:ast-grep']
description = 'Lint using ast-grep custom rules'
run = 'ast-grep scan'

[tasks.'test:plenary']
description = 'Test Neovim config using Plenary'
run = '''
nvim --headless -u NONE \
    -c 'set rtp+=~/.local/share/nvim/lazy/plenary.nvim' \
    -c 'runtime plugin/plenary.vim' \
    -c "PlenaryBustedDirectory ${1-tests/} { minimal_init = 'tests/minimal_init.lua' }"
'''
