#!/bin/sh
exec nvim --headless -u NONE \
    -c 'set rtp+=~/.local/share/nvim/lazy/plenary.nvim' \
    -c 'runtime plugin/plenary.vim' \
    -c "PlenaryBustedDirectory ${1-tests/} { minimal_init = 'tests/minimal_init.lua' }"
