name: Check ast-grep linter rules

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  ast-grep-lint:
    runs-on: ubuntu-latest
    name: Run ast-grep lint
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: ast-grep/action@v1.5.0
