name: Check Lua Formatting

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Stylua Check
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
