name: Test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel testing of a previous commit for the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Cache Lazy plugins
        uses: actions/cache@v4
        with:
          path: ~/.local/share/nvim/lazy*
          key: v1-lazy-${{ runner.os }}-${{ hashFiles('lazy-lock.json') }}

      - name: Install Lazy plugins
        run: |
          mkdir -p ~/.config
          ln -snf "$PWD" ~/.config/nvim
          nvim --headless -c "Lazy restore" +qa

      - run: mise run test
